### ISSUE TITLE
Helm post-rendering breaks resources outside release namespace

### ISSUE THREAD

**Issue by LittleFox94** [DoodleScheduling/flux-build#41]
Hi,

when building a `HelmRelease` from a helm chart that has resources outside the release namespace, the post-rendering will forcefully move those resources to the release namespace.

In our case we have two Roles with the same name, one in the release namespace and another one in `kube-public`. Due to both being in the same namespace now, there is an ID conflict - but even without that ID conflict, the deployment does not look the same as Flux applies this `HelmRelease`.

I'm not sure why this post-rendering was added, but at the very least, it should only apply to resources without an explicitly configured namespace? Should this done to the manifests rendered by Helm at all?

Otherwise a really useful piece of software, gonna help us a lot - found it via your comment on fluxcd/flux2 issue 2808 (not a link on purpose, to not link this on that issue), many thanks for that :)

**Comment by raffis** [comment]
The reason the post renderer is there if a helm template has no namespace the built resource will end up having the namespace from the kustomization. But I agree if the resource has a declared namespace in the template it should not be touched.
I will declare this a bug.
