### ISSUE TITLE
HelmRelease sourceRef namespace should be HelmRelease namespace by default

### ISSUE THREAD

**Issue by yoadey** [DoodleScheduling/flux-build#70]
In Flux, if you don't have any sourceRef set in HelmReleases `.spec.chart.spec.sourceRef.namespace`, it searches for the source in the same Namespace.

Currently, if a Namespace is not set, flux-build just fails with "no source `HelmRepository.source.toolkit.fluxcd.io` found for helmrelease"

**Comment by raffis** [comment]
Makes sense, will look into it 👍🏻
